version: '3.8'

services:
  recipes-api:
    container_name: recipes-api
    build:
      context: ./
    ports:
      - 80:80
      - 443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=<provide-your-password-here>
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro

  elastic-search:
    container_name: elastic-search
    image: elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    container_name: recipes_search
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"


volumes:
 esdata: {}