version: '3.8'

services:
#  RecipesApp:
#    depends_on:
#      - db
#      - es
#    ports:
#      - "8000:8000"
#    environment:
#      - LOGSTASH_HOST=logstash
#    expose:
#      - "5959"
#    logging:
#      driver: "json-file"

  es:
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    image: elasticsearch:5.4
    container_name: recipes_search
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"


volumes:
 esdata: {}