version: '3.8'

services:
 
  recipesdb:
    image: mongo:4.4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - dbdata:/data/db
    ports:
      - 8081:8081

    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example
  es:
    labels:
      com.example.service: "es"
      com.example.description: "For searching and indexing data"
    image: elasticsearch:5.4
    container_name: recipes_search
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"
  logstash:
    container_name: recipes_logstash
    labels:
      com.example.service: "logstash"
      com.example.description: "For logging data"
    image: logstash:5.4.3
    volumes:
      - ./:/logstash_dir
    command: logstash -f /logstash_dir/logstash.conf
    depends_on:
    - es
    ports:
      - "5959:5959"
#  RecipesApp:
#    depends_on:
#      - db
#      - es
#    ports:
#      - "8000:8000"
#    environment:
#      - LOGSTASH_HOST=logstash
#    expose:
#      - "5959"
#    logging:
#      driver: "json-file"

volumes:
 dbdata: {}
 esdata: {}